src/b.rs
If an immediate value is bigger than 2**32-1, the `lsl 16` for the next chunk will overwrite previously written value in bits 16-31.
Added `16 * i` instead, because `lsl` takes 0, 16, 32 or 48 as an argument.
=> Correct offsets for large immediate values

.gitignore, examples/.gitignore
Basically, anything which is not a `b` file in `examples` is filtered out from the folder.
=> Fix issues with files being tracked by git.

Makefile
The `modify date` of the `build` directory never gets updated after initial creation,
so all the `build/*.o` files have a newer `modify date` than the `build` directory at all times,
which causes `make` to re-compile them every single time.
from the [official make documentation](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types), we can use the `|` pipe operator, defining an `order-only prerequisites`,
so `make` will only check `$(BUILD)` existence and not it's `modify date`, giving proper incremental builds.
---
Updated the `$(BUILD)/b` rule dependencies list, added the following files:
1. `$(SRC)/arena.rs`
2. `$(SRC)/flag.rs`
3. `$(SRC)/codegen/fasm_x86_64_linux.rs`
4. `$(SRC)/codegen/gas_aarch64_linux.rs`
5. `$(SRC)/codegen/html_js.rs`
6. `$(SRC)/codegen/ir.rs`
7. …
=> Fix make incremental builds

src/codegen/html_js.rs
Update js target to be able to run examples 1, 2, 3 and 4.
sorry I started working on this before [c4b0bbf](https://github.com/tsoding/b/commit/c4b0bbf3ae7416ec6bbc2e9c72f9cfcaf71ec01f) and couldn't rebase it properly so everything is in a single commit now.
List of changes:
1. Use [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) for memory (both static memory and heap), which allow us to use [DataView.getBigUint64](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getBigUint64), [DataView.setBigUint64](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setBigUint64), [ArrayBuffer.resize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/ …
=> Update js target

src/codegen/gas_aarch64_linux.rs
TODOs for AArch64:
* Implemented pointers and bit operations
* Implemented unary not
* Implemented storing function call results
* Fixed less than operation (it was doing unsigned less or equal)
With these I'm seeing examples 1-4 all compiling and working as expected.
=> AArch64 TODOs

src/codegen/ir.rs
=> Display IR data section in hex editor style

src/b.rs, tests/assign_ref.b
tested the following example on both `fasm-x86_64-linux` and `html-js`
```c
main() {
extrn printf, malloc;
auto v;
v = malloc(8);
printf("v=%lu\n", v);
*v =   1;  printf("*v =   1    v=%d\n", *v);
*v |=  16; printf("*v |=  16   v=%d\n", *v);
*v *=  2;  printf("*v *=  2    v=%d\n", *v);
*v +=  35; printf("*v +=  35   v=%d\n", *v);
*v <<= 1;  printf("*v <<= 1    v=%d\n", *v);
}
```
=> Implement Assign{BitOr,BitShl,Plus,Mult} for Arg::Ref

src/b.rs, src/codegen/fasm_x86_64_linux.rs, src/codegen/gas_aarch64_linux.rs, src/codegen/html_js.rs, src/codegen/html_js_template.tt, src/codegen/ir.rs, tests/assign_ref.b, tests/compare.b, tests/gteq.b
Add `==` and `!=` binary operations 
Notes:
* lower precedence than `<` , `<=` , `>` and`>=` , based on B language reference (also the same in C).
* I can't test the `aarch64` target, and it's implementation is just a guess based on the implementation of `Less` and [this page](https://www.scs.stanford.edu/~zyedidia/arm64/cset_csinc.html).
=> Add equality checks

src/b.rs, src/crust.rs
This is more of a workaround than a proper fix...
basically, if the path does not contain `/` anywhere, add `./` at the start 
path | works by default | contains `/`
-|-|-
examples/program | :white_check_mark: | :white_check_mark: 
./examples/program | :white_check_mark: | :white_check_mark: 
../examples/program | :white_check_mark: | :white_check_mark: 
/usr/bin/program | :white_check_mark: | :white_check_mark: 
../program | :white_check_mark: | :white_check_mark: 
./program | :white_check_mark: | :white_check_mark: 
program | :x: | :x: 
although this "fix" is linux specific, windows is not a supported target right now so it should be fine. 
an alternative to this would be to call [`realpath(3)`](https://man7.org/linux/man-pages/man3/realpath.3.html), which is also POSIX specific, and …
=> "Fix" -run flag with files in the current directory

src/b.rs, src/codegen/html_js_template.tt, tests/hello.b, thirdparty/stb_c_lexer.h
also add `%c` support to printf in html-js target 
as for the workaround, it's needed to fix the following behavior 
```c
printf("%cello, %d\n", 'H', 'E'); // doesn't work
printf("%cello, %d\n", 'H' , 'E' ); // works
printf("%cello, %d\n", 'H'?, 'E'?); // works 
```
=> Add support for character literals

src/b.rs, src/codegen/fasm_x86_64_linux.rs, src/codegen/gas_aarch64_linux.rs, src/codegen/html_js.rs, src/codegen/ir.rs, tests/return.b
~~I removed the default return value of 0 so now using the return value of a function without a `return` statement is UB. I tried to look through the B manual to see if there was supposed to be some implicit return value, but couldn't find any mention.~~
~~Could be a bit smarter with the assembly by not generating the jump if return is the last statement already, but I figured to just keep it simple for now.~~
Tested with new `tests/return.b` on all platforms.
=> Implement return statements

src/b.rs, src/codegen/fasm_x86_64_linux.rs, tests/vector.b
as I already mentioned in the discord server, it does not take the machine word size into account, so `*(A+B)` and `A[B]` are identical.
=> Add vector syntax for expressions

src/b.rs, src/codegen/fasm_x86_64_linux.rs, src/codegen/gas_aarch64_linux.rs, src/stb_c_lexer.rs, thirdparty/stb_c_lexer.h
Updated stb_c_lexer_get_location to operate on input_stream instead of stb_lexer.
this still doesn't feel like the best solution to me, maybe the lexer should keep track of newlines as it processes the input ...
=> Only call stb_c_lexer_get_location in case of an error

src/codegen/mod.rs
```
warning: implicit autoref creates a reference to the dereference of a raw pointer
--> src/codegen/mod.rs:33:17
|
33 |     for i in 0..(*TARGET_NAMES).len() {
|                 ^^^^^^^^^^^^^^^^^^^^^
|
= note: creating a reference requires the pointer target to be valid and imposes aliasing requirements
= note: `#[warn(dangerous_implicit_autorefs)]` on by default
help: try using a raw pointer method instead; or if this reference is intentional, make it explicit
|
33 |     for i in 0..(&(*TARGET_NAMES)).len() {
|   
```
=> Fix dangerous_implicit_autorefs warning

Makefile, src/b.rs, src/codegen/fasm_x86_64_linux.rs, src/codegen/gas_aarch64_linux.rs, src/codegen/ir.rs, tests/ternary.b
* the `gas_aarch64_linux` is NOT tested, and it's implementation is based on the [`output of Compiler Explorer`](https://godbolt.org/z/q54qa5845) 
it's implemented in `compile_expression` instead of `compile_primary_expression`,
because it'd incorrectly parse `a == b ? c : d` as `a == (b ? c : d)` instead of `(a == b) ? c : d`
=> Add ternary operator `a ? b : c`

examples/uxn/02_screen.b, src/codegen/uxn.rs
I'm not sure that from B's perspective passing a function address like this:
```
uxn_deo2(0x20, &on_screen);
```
is more correct than this:
```
uxn_deo2(0x20, on_screen);
```
but at least now I can get rid of a hack in external arg loading which special cased functions
Also sneaks a fix for a previously broken Op::Store in uxn codegen.
=> uxn target: ref support

src/codegen/uxn.rs
Fixes `-C opt-level=0` breaking uxn because very rust, much safe
=> uxn codegen: fix panic: attempt to subtract with overflow

Makefile, src/b.rs, src/lexer.rs, tests/lexer.b
Miscellaneous lexer tweaks I noticed while reviewing #70. I tried to keep the commits separate so you can easily revert any you don't like.
* Added octal literals
* Added reporting for start of unfinished literals
* Fixed off-by-one in multicharacter literal packing
* Removed TODO for packing as order seems correct, see this [note](https://en.cppreference.com/w/cpp/language/character_literal.html#Notes) about C/C++ inheriting their order from B.
>  most compilers (MSVC is a notable exception) implement multicharacter literals as specified in B: the values of each char in the literal initialize successive bytes of the resulting integer, in big-endian zero-padded right-adjusted order
* Simplified comment handling
* Added null character escaping
=> Lexer tweaks

src/b.rs, src/codegen/fasm_x86_64_linux.rs, src/codegen/gas_aarch64_linux.rs, src/codegen/ir.rs, src/codegen/uxn.rs, src/lexer.rs, tests/asm.b
=> __asm__ function

src/b.rs
This pull request removes the `// TODO: decipher sections 3.0 and 4.2 of the B user manual` comment in the `Token::And` case of the `compile_primary_expression` function. The current implementation already aligns with the B user manual, specifically sections 3.0 and 4.2, and no further deciphering is necessary. Below, I provide extracts from the manual and explain how they map to the source code.
---
- **Manual Quote (Section 3.0)**:
> "The unary operator `&` can be used to interpret an lvalue as an rvalue. Thus `&x` evaluates the expression `x` as an lvalue. The application of `&` then yields the lvalue as an rvalue. The operator `&` can therefore be thought of as the address function."
- **Mapping to Code**:
The implementation ensures that the `&` operator is only applied to lvalues. If …
=> Remove TODO comments regarding sections 3.0 and 4.2 of the B user manual

Makefile, src/b.rs, tests/ternary-assign.b
fixes a bug where the following expression
```
a = b ? c : d;
```
would be parsed as 
```
(a=b) ? c : d;
```
instead of 
```
a = (b ? c : d);
```
originally discovered while working on #80
=> Fix ternary operator precedence

src/codegen/uxn.rs, std/uxn.b
Makes div and mod operations signed in uxn, which fixes `tests/divmod`
uxn's printf now uses %d to print signed numbers and %u for unsigned
Also fixes printf bug of consuming an arg when reading `%%`
=> uxn: signed div, mod, minor printf fixes

src/b.rs
Just a minor typo fix: "Expected ... by got ..." -> "Expected ... but got ..."
=> Fix typo in error message

src/b.rs, src/codegen/fasm_x86_64.rs, src/codegen/gas_aarch64_linux.rs, src/codegen/ir.rs, src/codegen/uxn.rs, src/lexer.rs
@yui-915 @deniska @mikmart @Miezekatze64 Please let me know what you think about this? Do you notice any UX problems?
=> Continue compilation for as long as possible

src/codegen/fasm_x86_64.rs, tests/call_stack_args.b
Alignment to 16 byte boundary on a function call is required by the [ABI](https://en.wikipedia.org/wiki/X86_calling_conventions#List_of_x86_calling_conventions) on both Linux and Windows.
Fixes #131.
=> x86-64: Align stack before function calls

libb/6502.b, src/codegen/mos6502.rs
Implemented other instructions to fix more 6502 tests.
Some of the functions where implemented in `libb/6502.b` and because of that I was able to implement functions like printf but still got some basic Op not completely implemented.
Some of them not work completely well for some reasons, like the usage of globals.
We can keep it open until I, or someone else, doesn't fix them.
=> Fix other tests of mos6502

src/b.rs
Maybe there should be a separate target for this like gas_aarch64_android. But Android is Linux anyway, so the codegen would be the same, calling convention is also the same.
`-fPIC` was added because of this error:
```shell
$ ./main
"./main": error: Android 5.0 and later only support position-independent
executables (-fPIE).
```
=> Fix linking on Android (Termux)

src/b.rs, src/codegen/fasm_x86_64.rs, src/codegen/gas_aarch64_linux.rs, src/codegen/gas_x86_64.rs, src/codegen/ir.rs, src/codegen/mos6502.rs, src/crust.rs, tests/asm_6502.b, tests/asm_func_6502.b
This pull request introduces inline assembly for the 6502 target and also changes the way opcodes are emitted
(separation of instructions and addressing modes).
All documented instructions and addressing modes are supported.
```c
__asm__(
"LDA #$10",
"LDX #10",
"STA 10,X",
"LDA #$04",
"INX",
"STA 10,X",
"LDX #69",
"STX $420",
"LDY #$10",
"LDA (20),Y",
"JMP ($FFFC)"
);
```
The assembly does not yet support labels or incorporation of B variables.
=> Introducing inline assmbly for 6502 target

libb/uxn.b
This fixes a bug in the `toupper()` function in `libb/uxn.b`.
The previous line
```c
if ('a' <= c && c <= 'z')
```
means `a <= c` and `(&c) <= z` instead of the intended `a <= c` and `c <= z`  it compiles to the IR:
```
auto[3] = ref auto[1] < 122
```
=> Fix toupper in libb/uxn.b

Makefile, README.md, src/btest.rs, src/glob.rs, src/nob.rs, thirdparty/glob.c, thirdparty/glob.h
This PR adds globbing support to the `-t` and `-c` flags in `btest` via [glob.h](https://github.com/tsoding/glob.h).
``` console
$ build/btest -t *linux -c *linux
K - success
B - failed to build
R - runtime error
┌─fasm-x86_64-linux       K: 2   B: 2   R: 0  
│ ┌─gas-x86_64-linux      K: 2   B: 2   R: 0  
│ │ ┌─gas-aarch64-linux   K: 0   B: 4   R: 0  
asm_fasm_x86_64_linux: K B B
asm_func_fasm_x86_64_linux: K B B
asm_func_gas_x86_64_linux: B K B
asm_gas_x86_64_linux: B K B
│ │ └─gas-aarch64-linux   K: 0   B: 4   R: 0  
│ └─gas-x86_64-linux      K: 2   B: 2   R: 0  
└─fasm-x86_64-linux       K: 2   B: 2   R: 0  
K - success
B - failed to build
R - runtime error
```
=> btest: Introduce globbing for targets and tests

src/b.rs, src/codegen/fasm_x86_64.rs, src/codegen/gas_aarch64.rs, src/codegen/gas_x86_64.rs, src/codegen/ir.rs, src/codegen/mos6502.rs, src/codegen/uxn.rs, src/targets.rs
Not sure if the 6502 implementation is 100% correct or is the most efficient (never touched this target before, code is based on the implementation of Op::Shl and Op::Add and [`this page`](https://www.masswerk.at/6502/6502_instruction_set.html), as compiler explorer didn't give me any meaningful output), but the tests are passing.
also removed the problematic `word_size()` function.
=> Introduce Op::Index

examples/dc.b
It's a fairly long implementation for dc, with bignum support, and it should be rather portable (although some platforms may require an actual `getchar` implementation, heap functions and `memset`/`memcpy`
I'm marking it as a draft mainly because the scale/decimal point feature isn't implemented yet, but integer math actually works quite well
=> examples: implement dc

examples/mandelbrot.b
This adds a simple fixed-precision floating point Mandelbrot set example:
=> Add Mandelbrot set example

src/b.rs, src/codegen/gas_aarch64.rs, src/codegen/gas_x86_64.rs, src/codegen/ilasm_mono.rs, src/codegen/mos6502.rs, src/codegen/uxn.rs
as suggested by #247. 
added the minimum amount of code required to make gdb report useful information on segfaults, which is a huge QoL change (at least for me). 
the `gas-x86_64-windows` target can be debugged using `winedbg --gdb main.exe`
I can't test the `gas-x86_64-darwin` target.
as already mentioned in https://github.com/tsoding/b/issues/247#issuecomment-3092390369, the compiler currently does not provide `source variables` -> `IR auto_vars` mappings, so line information is the best we can do without any IR changes. 
also should debug info not be enabled by default, and require a flag like `-g` instead ?
=> Add debug line information for gas-x86_64-*

src/b.rs
it should be processes before codegens parse their arguments.
=> fix `-L` flag

examples/uxn/callable_globals.b, examples/uxn/hello.b, examples/uxn/screen.b, libb/uxn.b, src/codegen/gas_x86_64.rs, src/codegen/uxn.rs, tests.json, tests/asm_func_uxn.b, tests/asm_uxn.b
Introduce a simple inline assembly for uxn target. Syntax is custom (compared to uxnasm), but it resembles other "traditional" assembly languages.
Make `uxn::generate_program` return an `Option` so now codegen can fail gracefully (e.g. when encountering an assembly error or an unknown extrn), instead of calling `abort()`.
Move "magic" uxn platform functions from `generate_extrns` to `libb/uxn.b` implemented in that inline asm.
Now that functions like `uxn_deo` live in `libb`, ensure that uxn-specific examples work when compiled with libb (without `-nostdlib` flag).
Make `libb/uxn.b` nicer by using features which were introduced after it was initially written: global initialization, extrn-less out of order func calls.
=> uxn inline assembly

src/b.rs, src/btest.rs, src/codegen/gas_aarch64.rs, src/codegen/gas_x86_64.rs, src/codegen/ilasm_mono.rs, src/codegen/mod.rs, src/codegen/mos6502.rs, src/codegen/noop.rs, src/codegen/uxn.rs, src/ir.rs, src/params.rs, src/targets.rs
This is a pivotal PR that fundamentally changes the interface between the compiler and the codegens. Now the codegens are way more decoupled from the compiler and provide their APIs as a structure of function pointers.
@yui-915 @deniska @Miezekatze64 @seija-amanojaku please let me know if you see any problems in this approach.
=> Target as a Structure of Function Pointers

examples/dc.b
This fixes a minor case where operations like
```
4 1/p
8 1/p
```
instead of their intended result (4 and 8)
=> examples: fix dc division

.github/workflows/ci.yml, tests/ref.b
The `ref.b` test was written before indexing became word-based, and didn't get updated afterwards.
it worked on all of the current targets because they don't have very stricts memory bounds check, but fails on the javascript target I'm working on because it tries to access unallocated memory.
=> Fix ref.b test
